'use client';

import { useMatchStore } from '@/stores/match-store';
import { useSettingsStore } from '@/stores/settings-store';
import { Share2, FileText, Download, MessageCircle, Send, Users } from 'lucide-react';

type ReportFormat = 'whatsapp' | 'twitter' | 'facebook' | 'website' | 'pdf';

export default function ReportGenerator() {
  const match = useMatchStore((s) => s.match);
  const accessibilityMode = useSettingsStore((s) => s.accessibilityMode);

  const rainMode = accessibilityMode === 'rain-mode';
  const highContrast = accessibilityMode === 'high-contrast';
  const largeText = accessibilityMode === 'large-text';

  if (!match) {
    return (
      <div className={`rounded-xl border-2 p-4 text-center ${highContrast ? 'border-black' : 'border-gray-300'}`}>
        <p className="text-gray-500">Start a match to generate reports.</p>
      </div>
    );
  }

  // Calculate scores
  const homeTotal = match.teamHome.goals * 3 + match.teamHome.points;
  const awayTotal = match.teamAway.goals * 3 + match.teamAway.points;

  // GAA notation helper: "1-13" format
  const gaaNotation = (goals: number, points: number) => `${goals}-${points}`;

  // Count events by type
  const scoreEvents = match.events.filter(e => e.type === 'score');
  const cardEvents = match.events.filter(e => ['yellow_card', 'black_card', 'red_card'].includes(e.type));
  const subEvents = match.events.filter(e => e.type === 'substitution');

  // Top scorers (by player index)
  const scorerMap: Record<number, { goals: number; points: number }> = {};
  scoreEvents.forEach(event => {
    if (event.playerIndex !== undefined) {
      if (!scorerMap[event.playerIndex]) {
        scorerMap[event.playerIndex] = { goals: 0, points: 0 };
      }
      const subtype = event.details?.subtype;
      if (subtype === 'goal') {
        scorerMap[event.playerIndex].goals++;
      } else {
        scorerMap[event.playerIndex].points += event.details?.isTwoPoint ? 2 : 1;
      }
    }
  });

  const topScorers = Object.entries(scorerMap)
    .map(([index, stats]) => ({ index: Number(index), ...stats }))
    .sort((a, b) => (b.goals * 3 + b.points) - (a.goals * 3 + a.points))
    .slice(0, 5);

  // Generate report content based on format
  const generateReport = (format: ReportFormat): string => {
    const homeName = match.teamHome.name;
    const awayName = match.teamAway.name;

    switch (format) {
      case 'whatsapp':
        return `⚽ MATCHDAY GAA REPORT ⚽\n\n` +
          `🏆 FINAL SCORE\n` +
          `${homeName} ${gaaNotation(match.teamHome.goals, match.teamHome.points)} (${homeTotal}) — ${gaaNotation(match.teamAway.goals, match.teamAway.points)} ${awayName} (${awayTotal})\n\n` +
          `📊 TOP SCORERS:\n` +
          (topScorers.length > 0 
            ? topScorers.map((s, i) => `  ${i + 1}. Player ${s.index + 1} — ${s.goals}G ${s.points}P (${s.goals * 3 + s.points} pts)`).join('\n')
            : '  No scores recorded'
          ) + `\n\n` +
          `🟨 CARDS: ${cardEvents.length}\n` +
          `🔄 SUBS: ${subEvents.length / 2 || Math.floor(subEvents.length / 2)}\n\n` +
          `_Generated by MatchDay GAA_`;

      case 'twitter':
        const tweetText = `FINAL SCORE: ${homeName} ${gaaNotation(match.teamHome.goals, match.teamHome.points)} — ${gaaNotation(match.teamAway.goals, match.teamAway.points)} ${awayName}\n` +
          `${homeTotal} pts — ${awayTotal} pts\n\n` +
          `🟨 Cards: ${cardEvents.length} | 🔄 Subs: ${Math.floor(subEvents.length / 2)}`;
        // Truncate to 280 chars if needed
        return tweetText.length > 280 ? tweetText.substring(0, 277) + '...' : tweetText;

      case 'facebook':
        return `🏆 MATCH REPORT\n\n` +
          `Final Score: ${homeName} ${gaaNotation(match.teamHome.goals, match.teamHome.points)} (${homeTotal}) — ${gaaNotation(match.teamAway.goals, match.teamAway.points)} (${awayTotal}) ${awayName}\n\n` +
          `📊 Top Scorers:\n` +
          (topScorers.length > 0 
            ? topScorers.map((s) => `• Player ${s.index + 1}: ${s.goals}G ${s.points}P`).join('\n')
            : '  No scores recorded'
          ) + `\n\n` +
          `🟨 Cards: ${cardEvents.length}\n` +
          `🔄 Substitutions: ${Math.floor(subEvents.length / 2)}\n\n` +
          `_Generated by MatchDay GAA_`;

      case 'website':
        return `<h2>Match Report</h2>\n` +
          `<p><strong>${homeName}</strong> ${gaaNotation(match.teamHome.goals, match.teamHome.points)} (${homeTotal}) — ${gaaNotation(match.teamAway.goals, match.teamAway.points)} <strong>${awayName}</strong></p>\n` +
          `<ul>\n` +
          `  <li>Total Scores: ${scoreEvents.length}</li>\n` +
          `  <li>Cards: ${cardEvents.length}</li>\n` +
          `  <li>Substitutions: ${Math.floor(subEvents.length / 2)}</li>\n` +
          `</ul>`;

      case 'pdf':
        return `MATCHDAY GAA — FULL MATCH REPORT\n${'='.repeat(50)}\n\n` +
          `FINAL SCORE: ${homeName} ${gaaNotation(match.teamHome.goals, match.teamHome.points)} (${homeTotal}) — ${gaaNotation(match.teamAway.goals, match.teamAway.points)} (${awayTotal}) ${awayName}\n\n` +
          `MATCH DETAILS:\n` +
          `  Sport: ${match.sport === 'gaelic-football' ? 'Gaelic Football' : 'Hurling'}\n` +
          `  Duration: ${match.halfDuration} min/half\n` +
          (match.venue ? `  Venue: ${match.venue}\n` : '') +
          (match.referee ? `  Referee: ${match.referee}\n` : '') +
          `\nEVENT TIMELINE:\n${match.events.map(e => `${e.minute}' [${e.teamSide === 'home' ? match.teamHome.name.substring(0, 3).toUpperCase() : match.teamAway.name.substring(0, 3).toUpperCase()}] ${e.type}`).join('\n')}\n\n` +
          `DISCIPLINE: ${cardEvents.length} card(s) issued\n` +
          `SUBSTITUTIONS: ${Math.floor(subEvents.length / 2)} change(s)`;

      default:
        return '';
    }
  };

  // Share via platform-specific links
  const shareReport = (format: ReportFormat) => {
    const content = generateReport(format);

    switch (format) {
      case 'whatsapp':
        window.open(`https://wa.me/?text=${encodeURIComponent(content)}`, '_blank');
        break;
      case 'twitter':
        window.open(`https://twitter.com/intent/tweet?text=${encodeURIComponent(content)}`, '_blank');
        break;
      case 'facebook':
        window.open(`https://www.facebook.com/sharer/sharer.php?quote=${encodeURIComponent(content)}`, '_blank');
        break;
      case 'website':
        navigator.clipboard.writeText(generateReport('website'));
        alert('HTML copied to clipboard — paste into your club website CMS.');
        break;
      case 'pdf':
        // Client-side PDF generation using jsPDF (to be installed)
        const blob = new Blob([generateReport('pdf')], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `match-report-${match.teamHome.name}-vs-${match.teamAway.name}.txt`;
        a.click();
        URL.revokeObjectURL(url);
        break;
    }
  };

  const reportFormats: { format: ReportFormat; label: string; icon: React.ReactNode; description: string }[] = [
    { format: 'whatsapp', label: 'WhatsApp', icon: <MessageCircle className="w-6 h-6" />, description: 'Group chat' },
    { format: 'twitter', label: 'X / Twitter', icon: <Send className="w-6 h-6" />, description: 'Public post' },
    { format: 'facebook', label: 'Facebook', icon: <Users className="w-6 h-6" />, description: 'Page share' },
    { format: 'website', label: 'Club Website', icon: <Share2 className="w-6 h-6" />, description: 'HTML snippet' },
    { format: 'pdf', label: 'PDF / Archive', icon: <FileText className="w-6 h-6" />, description: 'Full report' },
  ];

  return (
    <div className={`rounded-xl border-2 p-4 ${highContrast ? 'border-black' : 'border-gray-300'} ${rainMode ? 'bg-rain-bg p-6' : ''}`}>
      <h3 className={`${largeText ? 'text-xl' : 'text-lg'} font-bold text-gaa-green mb-4`}>
        Generate Report
      </h3>

      {/* Match Summary */}
      <div className={`mb-4 rounded-lg p-3 ${rainMode ? 'bg-rain-card' : ''}`}>
        <p className={`font-black text-center ${largeText ? 'text-xl' : ''}`}>
          {match.teamHome.name} {gaaNotation(match.teamHome.goals, match.teamHome.points)} — {gaaNotation(match.teamAway.goals, match.teamAway.points)} {match.teamAway.name}
        </p>
        <p className={`text-center text-sm text-gray-500 ${rainMode ? 'text-rain-sm' : ''}`}>
          {scoreEvents.length} scores • {cardEvents.length} cards • {Math.floor(subEvents.length / 2)} subs
        </p>
      </div>

      {/* Format Selection */}
      <div className="grid grid-cols-2 gap-3 mb-4">
        {reportFormats.map(({ format, label, icon, description }) => (
          <button
            key={format}
            onClick={() => shareReport(format)}
            className={`flex flex-col items-center gap-2 rounded-lg border-2 p-3 transition-all ${highContrast ? 'border-black hover:bg-gray-100' : 'border-gray-200 hover:border-gaa-green hover:bg-green-50'}`}
          >
            <span className="text-gaa-green">{icon}</span>
            <span className={`font-bold text-gray-900 ${largeText ? 'text-base' : ''}`}>{label}</span>
            <span className={`text-xs text-gray-500 ${rainMode ? 'text-sm' : ''}`}>{description}</span>
          </button>
        ))}
      </div>

      {/* Offline Queue Hint */}
      <p className={`mt-3 text-center text-xs text-gray-400 ${rainMode ? 'text-sm' : ''}`}>
        Reports generated offline are queued and sent when connectivity returns
      </p>
    </div>
  );
}
