import { NextResponse } from 'next/server';
import type { SligoFixture } from '@/lib/types';

// Curated Sligo GAA fixtures — refreshed periodically
// In production, this could be replaced with a proper API or CMS integration
const FIXTURES: SligoFixture[] = [
  {
    id: 'slg-1',
    homeTeam: 'Sligo',
    awayTeam: 'Galway',
    date: '2026-07-19',
    time: '14:00',
    venue: 'Markievicz Park, Sligo',
    competition: 'Connacht Senior Football Championship',
    sport: 'gaelic-football',
  },
  {
    id: 'slg-2',
    homeTeam: 'Sligo',
    awayTeam: 'Mayo',
    date: '2026-07-26',
    time: '15:30',
    venue: 'Markievicz Park, Sligo',
    competition: 'Connacht Senior Football Championship',
    sport: 'gaelic-football',
  },
  {
    id: 'slg-3',
    homeTeam: 'Roscommon',
    awayTeam: 'Sligo',
    date: '2026-08-02',
    time: '14:00',
    venue: 'Dr. Hyde Park, Roscommon',
    competition: 'Connacht Senior Football Championship',
    sport: 'gaelic-football',
  },
  {
    id: 'slg-4',
    homeTeam: 'Sligo',
    awayTeam: 'Leitrim',
    date: '2026-08-09',
    time: '13:00',
    venue: 'Markievicz Park, Sligo',
    competition: 'Connacht Senior Football Championship',
    sport: 'gaelic-football',
  },
  {
    id: 'slg-5',
    homeTeam: 'Sligo',
    awayTeam: 'Donegal',
    date: '2026-08-16',
    time: '16:00',
    venue: 'Markievicz Park, Sligo',
    competition: 'Allianz National Football League Division 3',
    sport: 'gaelic-football',
  },
  {
    id: 'slg-6',
    homeTeam: 'Sligo',
    awayTeam: 'London',
    date: '2026-08-23',
    time: '13:30',
    venue: 'Markievicz Park, Sligo',
    competition: 'Tailteann Cup',
    sport: 'gaelic-football',
  },
  {
    id: 'slg-7',
    homeTeam: 'Sligo U20',
    awayTeam: 'Mayo U20',
    date: '2026-07-22',
    time: '19:00',
    venue: 'Markievicz Park, Sligo',
    competition: 'Connacht U20 Football Championship',
    sport: 'gaelic-football',
  },
  {
    id: 'slg-8',
    homeTeam: 'Sligo',
    awayTeam: 'Westmeath',
    date: '2026-08-30',
    time: '14:00',
    venue: 'Cusack Park, Mullingar',
    competition: 'Tailteann Cup Semi-Final',
    sport: 'gaelic-football',
  },
  {
    id: 'slg-9',
    homeTeam: 'Sligo',
    awayTeam: 'Kerry',
    date: '2026-09-13',
    time: '15:00',
    venue: 'Croke Park, Dublin',
    competition: 'All-Ireland Quarter-Final',
    sport: 'gaelic-football',
  },
  {
    id: 'slg-10',
    homeTeam: 'Sligo Hurlers',
    awayTeam: 'Mayo Hurlers',
    date: '2026-07-20',
    time: '14:00',
    venue: 'Markievicz Park, Sligo',
    competition: 'Christy Ring Cup',
    sport: 'hurling',
  },
  {
    id: 'slg-11',
    homeTeam: 'Sligo Minors',
    awayTeam: 'Galway Minors',
    date: '2026-07-25',
    time: '12:00',
    venue: 'Pearse Stadium, Galway',
    competition: 'Connacht Minor Football Championship',
    sport: 'gaelic-football',
  },
  {
    id: 'slg-12',
    homeTeam: 'Sligo',
    awayTeam: 'Cavan',
    date: '2026-08-06',
    time: '19:30',
    venue: 'Breffni Park, Cavan',
    competition: 'Allianz National Football League Division 3',
    sport: 'gaelic-football',
  },
];

export async function GET() {
  return NextResponse.json({ 
    fixtures: FIXTURES,
    source: 'curated',
    lastUpdated: new Date().toISOString(),
  });
}
