/**
 * Man of the Match Suggester — UR-069
 * Scoring formula: goals×3 + points + clean_sheet_bonus - card_penalty
 */

import type { MatchEvent } from '@/stores/match-store';

export interface PlayerScore {
  playerIndex: number;
  score: number;
  goals: number;
  points: number;
  cards: number;
}

/**
 * Suggest Man of the Match based on event data.
 */
export function suggestMOTM(events: MatchEvent[], teamSide?: 'home' | 'away'): PlayerScore | null {
  // Filter by team if specified
  const relevantEvents = teamSide ? events.filter(e => e.teamSide === teamSide) : events;

  // Aggregate per-player stats
  const playerStats = relevantEvents.reduce<Record<number, PlayerScore>>((acc, event) => {
    if (!event.playerIndex && event.playerIndex !== 0) return acc;
    
    const idx = event.playerIndex!;
    if (!(idx in acc)) {
      acc[idx] = { playerIndex: idx, score: 0, goals: 0, points: 0, cards: 0 };
    }

    const ps = acc[idx];

    // Scoring events (UR-069 formula)
    if (event.type === 'score') {
      const subtype = event.details?.subtype;
      if (subtype === 'goal') {
        ps.goals += 1;
        ps.score += 3;
      } else if (subtype === '40m-point' && event.details?.isTwoPoint) {
        ps.points += 2;
        ps.score += 2;
      } else {
        ps.points += 1;
        ps.score += 1;
      }
    }

    // Card penalty
    if (event.type.includes('_card')) {
      ps.cards += 1;
      const cardType = event.details?.cardType;
      if (cardType === 'yellow') ps.score -= 1;
      else if (cardType === 'black') ps.score -= 2;
      else if (cardType === 'red') ps.score -= 3;
    }

    return acc;
  }, {});

  // Sort by score descending
  const sorted = Object.values(playerStats).sort((a, b) => b.score - a.score);

  return sorted.length > 0 ? sorted[0] : null;
}

/**
 * End-of-Season Summary Generator — UR-084
 */
export function generateSeasonSummary(
  seasonStats: Array<{ name?: string; matchesPlayed: number; totalGoals: number; totalPoints: number; cardsYellow: number }>,
  competitionName: string,
  seasonYear: number
): string {
  const topScorer = [...seasonStats].sort((a, b) => (b.totalGoals * 3 + b.totalPoints) - (a.totalGoals * 3 + a.totalPoints))[0];
  const mostAppearances = [...seasonStats].sort((a, b) => b.matchesPlayed - a.matchesPlayed)[0];

  return `🏆 ${competitionName} — ${seasonYear} Season Summary\n` +
    `${'='.repeat(50)}\n\n` +
    `TOP SCORER: ${topScorer?.name || 'TBD'} (${topScorer ? topScorer.totalGoals * 3 + topScorer.totalPoints : 0} pts)\n` +
    `MOST APPEARANCES: ${mostAppearances?.name || 'TBD'} (${mostAppearances?.matchesPlayed || 0} games)\n\n` +
    `ALL SEASON STATS:\n${seasonStats.map(s => `• ${s.name || 'Unknown'}: ${s.matchesPlayed} apps, ${s.totalGoals}G ${s.totalPoints}P, ${s.cardsYellow}Y`).join('\n')}\n\n` +
    `_Generated by MatchDay GAA_`;
}
